server:
 port: 3000

log:
 level: info
 tofile: false

sql:
 # mysql://user:pwd@host:port/db
 url: mysql://root:newpassword@192.168.1.199:3306/hello?rewriteBatchedStatements=true

 max_connections: 100
 min_connections: 10

redis:
 # redis://user:pwd@host:port/db
 #url: redis://:789789@192.168.1.199/