-- Your SQL goes here

CREATE TABLE posts (
  id BIGINT NOT NULL AUTO_INCREMENT,
  title VARCHAR(128) NOT NULL,
  body TEXT NOT NULL,
  published BOOLEAN NOT NULL DEFAULT 0,
  
  PRIMARY KEY(id)
);

CREATE TABLE users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(128) NOT NULL,
  age TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE short_links (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  url VARCHAR(128) NOT NULL,

  PRIMARY KEY(id)
);